### PR TITLE
[coq] Adapt to coq/coq#9173

### PR DESCRIPTION
**Pull request by ejgallego**
To be merged when the upstream PR is merged.

### CODE REVIEW

**Comment by JasonGross** [comment]
@ejgallego I think you transposed the issue number in the commit message; you mean https://github.com/coq/coq/pull/9173, right?

**Comment by ejgallego** [comment]
Indeed, thanks @JasonGross

**Comment by maximedenes** [comment]
Upstream PR was merged, can you merge this one? Thanks!

**Comment by ejgallego** [comment]
@JasonGross ping!

**Pull request merged**
