### PR TITLE
Fix adaptation to coq/coq#15220 (`sed` typoed to `set`)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by JasonGross** [comment]
File "./src/Common/Tactics/TransparentAbstract.v", line 1, characters 0-65:
Error:
Findlib error: coq-fiat-parsers.transparent_abstract_plugin not found in:
/home/coq/.opam/4.05.0/lib/coq/../coq-core/..
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Ltac2
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums/CyclicDouble
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums/BigZ
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums/SpecViaQ
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums/BigN
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums/SpecViaZ
/home/coq/.opam/4.05.0/lib/coq/user-contrib/Bignums/BigQ
src/Common/Tactics
/home/coq/.opam/4.05.0/lib

**Comment by SkySkimmer** [comment]
cc @gares

**Comment by gares** [comment]
This PR is clearly ok. I think there is a missing -I place-of-META.coq-fiat-parsers which got unnoticed before

**Review by JasonGross — CHANGES_REQUESTED** [review]
In that case, pease update the `-I` flag in `_CoqProject.in` to include the meta file

**Comment by SkySkimmer** [comment]
seems to work

**Review by gares — APPROVED** [review]

**Pull request merged**
