### PR TITLE
Remove uses of deprecated appcontext.

### PR DESCRIPTION
**Pull request by Zimmi48**
`appcontext` is likely to be removed in Coq 8.8 and is semantically equivalent to `context`

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Doesn't this break things? I'm still on 8.4

**Comment by Zimmi48** [comment]
Yes, I went ahead because @JasonGross told me that everybody had moved away from 8.4. If that's not the case, this patch should be limited only to the parts that have moved away.

**Comment by JasonGross** [comment]
@cpitclaudel Note that we do have a v8.4 branch meant for things that only build on 8.4.  Options I see:
1. Claim that the main part of fiat will never support Coq > 8.4, have the Coq CI follow a separate `parsers` branch.
2. Have you and anyone else still depending on the bits of Bedrock that only build in 8.4 switch to developing on the v8.4 branch of fiat
3. Find the uses of `appcontext` that are common between fiat-core/parsers and the stuff you work on and find a way to get the same effect with `context`

Also, according to travis, fiat-core does not even build with Coq < 8.6:
```
COQC src/QueryStructure/Specification/Representation/QueryStructure.v
File "/home/travis/build/mit-plv/fiat/src/QueryStructure/Specification/Representation/QueryStructure.v", line 279, characters 0-82:
Error: The following arguments are not declared: H, H0.
```

I've made #9, which changes only the files built by parsers, parsers-examples, and fiat-core.  @cpitclaudel , could you see if that's local enough for you, if you think 3 is the way to go?  (If you want to go with 1 or 2, I branch/merge.)

**Comment by cpitclaudel** [comment]
I expect #9 to be fine (does it get to the error above with appcontext? if so, it should be OK).  The broken build is due to a small oversight; I have a fix for that in my branch.

**Comment by Zimmi48** [comment]
I'm closing this because #9 is sufficient given what we test on the Coq Travis.

**Pull request closed without merging**
