### PR TITLE
Adapt w.r.t. coq/coq#16099.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Should be backwards compatible btw.

**Comment by ppedrot** [comment]
Hmm, this will need a synchronous coq-scripts bump.

**Comment by JasonGross** [comment]
Any idea what's up with the failing dev build?
```
COQ_IMAGE=coqorg/coq:dev
  Error response from daemon: manifest for coqorg/coq:dev not found: manifest unknown: manifest unknown
```

**Comment by ppedrot** [comment]
It seems to be a well-known problem, see e.g. https://github.com/fblanqui/color/pull/42#issuecomment-1141247333.

**Comment by JasonGross** [comment]
Please rebase on master one more time, the CI should work now

**Comment by ppedrot** [comment]
The CI seems to have passed correctly.

**Pull request merged**
