### PR TITLE
ML code compatibility for Coq PR # 6285

### PR DESCRIPTION
**Pull request by mattam82**
Do not merge yet. Follows coq/coq#6285

### CODE REVIEW

**Comment by JasonGross** [comment]
This seems wrong, I thought the ML API for Coq 8.13.X was frozen?  Should I split off the v8.14 files?

**Comment by mattam82** [comment]
Yes please, I didn't know how to do it and just wanted to check my PR was building correctly on the CI

**Comment by JasonGross** [comment]
Hopefully https://github.com/mit-plv/fiat/pull/51 should do the trick.  I'll merge it if it passes CI and then ask you to rebase this on top of that.

**Comment by JasonGross** [comment]
Please rebase on current master

**Comment by mattam82** [comment]
Thanks!

**Comment by JasonGross** [comment]
Choosing this as the Coq PR was closed in December 2021

**Pull request closed without merging**
