### PR TITLE
Fix w.r.t. coq/coq#12493.

### PR DESCRIPTION
**Pull request by ppedrot**
Should be backwards compatible.

### CODE REVIEW

**Comment by JasonGross** [comment]
What does whether or not arguments are passed to the lemma passed to `destruct` have to do with proxy hints?

**Comment by ppedrot** [comment]
Using constants seems to change the shape of the term being destructed over, which prevents from properly generalizing it.

**Comment by cpitclaudel** [comment]
> Should be backwards compatible.

In this particular case, right? In general this change could cause the wrong thing to be destructed.

**Comment by ppedrot** [comment]
@cpitclaudel yep.

**Pull request merged**
