### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
This is breaking backwards compatibility with older Coq versions. If you want to keep it this will require more infrastructure, e.g. with some file preprocessing.

**Comment by JasonGross** [comment]
No, I can just tag a release for old versions and drop compat.  Can you add `fail-fast: false` to both workflow files (9d425f88d52ede01142adf2cd0bddc6a9f25a33c shows where to add one of them) so that we can see which versions break?

**Comment by JasonGross** [comment]
Please rebase on current master.  I've dropped support for Coq < 8.11 and added unsupported-attributes which should fix 8.11--8.14 compat

**Comment by JasonGross** [comment]
Wait, no, I broke something in adding unsupported-attributes

**Comment by JasonGross** [comment]
Okay, if you rebase it should work now

**Comment by ppedrot** [comment]
CI green, AFAICT this is ready.

**Pull request merged**
